name: build and deploy

on: ["pull_request", "push"]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v6
      - name: install python version 3.11.9
        uses: actions/setup-python@v6
        with:
          python-version: "3.11.9"
      - name: install pip
        run: python -m pip --upgrade pip
      - name: install requirements
        run: pip install -r requirements.txt
      