name: build and deploy

on: ["pull_request", "push"]

jobs:
  job1:
    runs_on: ubuntu-latest
    steps:
      - name: pull code
        uses: actions/checkout@v6
      - name: say hi to me
        run: echo "hello Priyanshi"