name: build and deploy

on: [ "pull_request", "push" ]

jobs:
  build:
    environment: testing
    env:
      DATABASE_HOSTNAME: ${{ secrets.DATABASE_HOSTNAME }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
      DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d FastAPI_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: pull code
      uses: actions/checkout@v6
    - name: install python version 3.11.9
      uses: actions/setup-python@v6
      with:
        python-version: "3.11.9"
    - name: install pip
      run: python -m pip install --upgrade pip
    - name: install requirements
      run: pip install -r requirements.txt
    - name: run tests
      run: |
        pip install pytest
        pytest


    - name: docker login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: print docker login status
      run: docker login

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    
    - name: build and pushs
      uses: docker/build-push-action@v7
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/fastapi:buildcache,mode=max
        secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}


  deploy:
    needs: [build]
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout/pull code
      uses: actions/checkout@v6

    - name: Deploy to render
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api-key: ${{ secrets.MY_RENDER_API_KEY }}
        wait-for-success: true

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.UBUNTU_HOST }}
        username: ${{ secrets.UBUNTU_USERNAME }}
        password: ${{ secrets.UBUNTU_PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd app/src
          git pull
          echo ${{ secrets.UBUNTU_PASSWORD }} | sudo -S systemctl restart api




